
before_install:
  - gem install sass
  - git clone https://github.com/hcatlin/sass-spec.git
  - git clone https://github.com/hcatlin/sassc.git
  - export SASS_SPEC_PATH=sass-spec
  - export SASS_SPEC_PATH=sassc
script: "make test"
